from enum import StrEnum


class SimExecutionPolicy(StrEnum):
    IMMEDIATE_FULL_FILL = "IMMEDIATE_FULL_FILL"
    IMMEDIATE_REJECT = "IMMEDIATE_REJECT"
    PRE_SEND_TIMEOUT = "PRE_SEND_TIMEOUT"
    POST_SEND_UNCERTAIN = "POST_SEND_UNCERTAIN"
