from enum import StrEnum


class Direction(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class Offset(StrEnum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    CLOSE_TODAY = "CLOSE_TODAY"
    CLOSE_YESTERDAY = "CLOSE_YESTERDAY"


class OrderType(StrEnum):
    LIMIT = "LIMIT"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    RISK_CHECKING = "RISK_CHECKING"
    REJECTED_BY_RISK = "REJECTED_BY_RISK"
    RISK_ACCEPTED = "RISK_ACCEPTED"
    SUBMITTING = "SUBMITTING"
    SUBMIT_TIMEOUT = "SUBMIT_TIMEOUT"
    SUBMIT_FAILED = "SUBMIT_FAILED"
    SUBMITTED = "SUBMITTED"
    ACKED = "ACKED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCEL_FAILED = "CANCEL_FAILED"
    CANCELED = "CANCELED"
    FILLED = "FILLED"
    REJECTED_BY_EXCHANGE = "REJECTED_BY_EXCHANGE"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


class EventSource(StrEnum):
    STRATEGY = "STRATEGY"
    RISK = "RISK"
    OMS = "OMS"
    EMS = "EMS"
    EXCHANGE = "EXCHANGE"
    EXECUTION_REPORT_NORMALIZER = "execution_report_normalizer"
    SETTLEMENT = "SETTLEMENT"
    SYSTEM = "SYSTEM"


class RiskDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class EventApplicationStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    OLD_IGNORED = "OLD_IGNORED"
    MISMATCH_REJECTED = "MISMATCH_REJECTED"
    ENTERED_UNKNOWN = "ENTERED_UNKNOWN"
    RECOVERED_FROM_UNKNOWN = "RECOVERED_FROM_UNKNOWN"
    IGNORED_TERMINAL = "IGNORED_TERMINAL"
    EVENT_KEY_COLLISION = "EVENT_KEY_COLLISION"


class PositionManagerResultStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    REJECTED_INSUFFICIENT_POSITION = "REJECTED_INSUFFICIENT_POSITION"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class MarginPriceBasis(StrEnum):
    LAST_PRICE = "LAST_PRICE"
    SETTLEMENT_PRICE = "SETTLEMENT_PRICE"
    AVG_PRICE = "AVG_PRICE"
    MANUAL = "MANUAL"


class MarginResultStatus(StrEnum):
    CALCULATED = "CALCULATED"
    REJECTED_MISSING_RULE = "REJECTED_MISSING_RULE"
    REJECTED_MISSING_POSITION = "REJECTED_MISSING_POSITION"
    REJECTED_MISSING_PRICE = "REJECTED_MISSING_PRICE"
    REJECTED_INSUFFICIENT_CASH = "REJECTED_INSUFFICIENT_CASH"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class PnLPriceBasis(StrEnum):
    LAST_PRICE = "LAST_PRICE"
    SETTLEMENT_PRICE = "SETTLEMENT_PRICE"
    MANUAL = "MANUAL"


class PnLResultStatus(StrEnum):
    CALCULATED = "CALCULATED"
    REJECTED_MISSING_POSITION = "REJECTED_MISSING_POSITION"
    REJECTED_MISSING_PRICE = "REJECTED_MISSING_PRICE"
    REJECTED_MISSING_MULTIPLIER = "REJECTED_MISSING_MULTIPLIER"
    REJECTED_MISSING_FEE = "REJECTED_MISSING_FEE"
    DOMAIN_FIELD_UNSUPPORTED = "DOMAIN_FIELD_UNSUPPORTED"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class SettlementResultStatus(StrEnum):
    SETTLED = "SETTLED"
    DUPLICATE = "DUPLICATE"
    REJECTED_NON_TRADING_DAY = "REJECTED_NON_TRADING_DAY"
    REJECTED_MISSING_POSITION = "REJECTED_MISSING_POSITION"
    REJECTED_MISSING_PNL = "REJECTED_MISSING_PNL"
    REJECTED_MISSING_MARGIN = "REJECTED_MISSING_MARGIN"
    REJECTED_MISSING_SETTLEMENT_PRICE = "REJECTED_MISSING_SETTLEMENT_PRICE"
    REJECTED_FROZEN_POSITION = "REJECTED_FROZEN_POSITION"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class MarketDataResultStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED_MISSING_IDENTITY = "REJECTED_MISSING_IDENTITY"
    REJECTED_BAD_TIMESTAMP = "REJECTED_BAD_TIMESTAMP"
    REJECTED_OUT_OF_SESSION = "REJECTED_OUT_OF_SESSION"
    REJECTED_BAD_PRICE = "REJECTED_BAD_PRICE"
    REJECTED_NON_MONOTONIC = "REJECTED_NON_MONOTONIC"
    DUPLICATE = "DUPLICATE"
    GAP_DETECTED = "GAP_DETECTED"
    ERROR = "ERROR"


class MarketDataEventType(StrEnum):
    TICK_ACCEPTED = "TICK_ACCEPTED"
    BAR_ACCEPTED = "BAR_ACCEPTED"
    TICK_REJECTED = "TICK_REJECTED"
    BAR_REJECTED = "BAR_REJECTED"
    DUPLICATE = "DUPLICATE"
    GAP_DETECTED = "GAP_DETECTED"
    ERROR = "ERROR"


class FeatureQualityStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    WARMUP_INCOMPLETE = "WARMUP_INCOMPLETE"
    GAP_DETECTED = "GAP_DETECTED"


class FeatureResultStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    WARMUP_INCOMPLETE = "WARMUP_INCOMPLETE"
    REJECTED_EMPTY_INPUT = "REJECTED_EMPTY_INPUT"
    REJECTED_IDENTITY_MISMATCH = "REJECTED_IDENTITY_MISMATCH"
    REJECTED_TIMEFRAME_MISMATCH = "REJECTED_TIMEFRAME_MISMATCH"
    REJECTED_NON_MONOTONIC = "REJECTED_NON_MONOTONIC"
    REJECTED_GAP = "REJECTED_GAP"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class SignalDecisionType(StrEnum):
    HOLD = "HOLD"
    BUY = "BUY"
    SELL = "SELL"


class SignalSide(StrEnum):
    NONE = "NONE"
    BUY = "BUY"
    SELL = "SELL"


class SignalPositionSide(StrEnum):
    NONE = "NONE"
    LONG = "LONG"
    SHORT = "SHORT"


class SignalLifecycleStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    TRIGGERED = "TRIGGERED"
    DUPLICATE = "DUPLICATE"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"


class StrategyResultStatus(StrEnum):
    GENERATED = "GENERATED"
    REJECTED_DISABLED = "REJECTED_DISABLED"
    REJECTED_INVALID_CONTEXT = "REJECTED_INVALID_CONTEXT"
    REJECTED_INVALID_SIGNAL_ID = "REJECTED_INVALID_SIGNAL_ID"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class SignalResultStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
    TRIGGERED = "TRIGGERED"
    ERROR = "ERROR"


class RiskResultStatus(StrEnum):
    ACCEPT = "ACCEPT"
    REDUCE = "REDUCE"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    UNKNOWN = "UNKNOWN"


class TradingWorkflowResultStatus(StrEnum):
    INTENT_CREATED = "INTENT_CREATED"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_BLOCKED = "RISK_BLOCKED"
    RISK_UNKNOWN = "RISK_UNKNOWN"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class OMSBridgeResultStatus(StrEnum):
    CREATED = "CREATED"
    DUPLICATE = "DUPLICATE"
    REJECTED_INVALID_INTENT = "REJECTED_INVALID_INTENT"
    REJECTED_RISK_NOT_ACCEPTED = "REJECTED_RISK_NOT_ACCEPTED"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class ExecutionTarget(StrEnum):
    MOCK = "MOCK"
    PAPER = "PAPER"
    SIM = "SIM"
    LIVE = "LIVE"


class ExecutionCommandType(StrEnum):
    SUBMIT_ORDER = "SUBMIT_ORDER"
    CANCEL_ORDER = "CANCEL_ORDER"


class ExecutionCommandResultStatus(StrEnum):
    ACCEPTED_BY_ADAPTER = "ACCEPTED_BY_ADAPTER"
    REJECTED_BY_ADAPTER = "REJECTED_BY_ADAPTER"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class ExecutionGatewayResultStatus(StrEnum):
    COMMAND_CREATED = "COMMAND_CREATED"
    DUPLICATE = "DUPLICATE"
    REJECTED_UNSUPPORTED_TARGET = "REJECTED_UNSUPPORTED_TARGET"
    REJECTED_INVALID_ORDER = "REJECTED_INVALID_ORDER"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class ExecutionReportStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    ACKED = "ACKED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELED = "CANCELED"
    ERROR = "ERROR"


class ExecutionReportNormalizeResultStatus(StrEnum):
    NORMALIZED = "NORMALIZED"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    REJECTED_INVALID_REPORT = "REJECTED_INVALID_REPORT"
    ERROR = "ERROR"


class OMSEventApplyResultStatus(StrEnum):
    APPLIED = "APPLIED"
    DRY_RUN = "DRY_RUN"
    NO_OP = "NO_OP"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    REJECTED_INVALID_CANDIDATE = "REJECTED_INVALID_CANDIDATE"
    REJECTED_NO_EVENT = "REJECTED_NO_EVENT"
    ERROR = "ERROR"


class BarTimeframe(StrEnum):
    M1 = "M1"
    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    D1 = "D1"
