from enum import StrEnum


class Direction(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class Offset(StrEnum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    CLOSE_TODAY = "CLOSE_TODAY"
    CLOSE_YESTERDAY = "CLOSE_YESTERDAY"


class OrderType(StrEnum):
    LIMIT = "LIMIT"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    RISK_CHECKING = "RISK_CHECKING"
    REJECTED_BY_RISK = "REJECTED_BY_RISK"
    RISK_ACCEPTED = "RISK_ACCEPTED"
    SUBMITTING = "SUBMITTING"
    SUBMIT_TIMEOUT = "SUBMIT_TIMEOUT"
    SUBMIT_FAILED = "SUBMIT_FAILED"
    SUBMITTED = "SUBMITTED"
    ACKED = "ACKED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCEL_FAILED = "CANCEL_FAILED"
    CANCELED = "CANCELED"
    FILLED = "FILLED"
    REJECTED_BY_EXCHANGE = "REJECTED_BY_EXCHANGE"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


class EventSource(StrEnum):
    STRATEGY = "STRATEGY"
    RISK = "RISK"
    OMS = "OMS"
    EMS = "EMS"
    EXCHANGE = "EXCHANGE"
    SETTLEMENT = "SETTLEMENT"
    SYSTEM = "SYSTEM"


class RiskDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class EventApplicationStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    OLD_IGNORED = "OLD_IGNORED"
    MISMATCH_REJECTED = "MISMATCH_REJECTED"
    ENTERED_UNKNOWN = "ENTERED_UNKNOWN"
    RECOVERED_FROM_UNKNOWN = "RECOVERED_FROM_UNKNOWN"
    IGNORED_TERMINAL = "IGNORED_TERMINAL"
    EVENT_KEY_COLLISION = "EVENT_KEY_COLLISION"


class PositionManagerResultStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    REJECTED_INSUFFICIENT_POSITION = "REJECTED_INSUFFICIENT_POSITION"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"
